spring:
  application:
    name: order-importer-api
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  jpa:
    show-sql: true

logging:
  level:
    br.com.akj.order: DEBUG

### LIQUIBASE ###
liquibase:
  enabled: true
  liquibase-schema: hello-user
